Update work GitHub Actions
knpuniversity/oauth2-client-bundle pull request #289
Opened 2021-03-04 16:42 UTC by Yozhef

2021-03-04 17:37 UTC, Yozhef commented
my suggestion to refuse the service flintci / pr - from contributors does not give clarity of check whether they adhered to the project style code, as well as to add a free service codecov to measure test coverage

2021-03-19 15:23 UTC, Yozhef commented
@weaverryan any idea how to speed up the review stage?

2021-03-22 00:55 UTC, weaverryan commented
Ah, sorry about that! Let me ping my colleague - he's my GH actions expert on our other tutorial - ping @jrushlow :)

2021-03-22 10:45 UTC, jrushlow requested changes
Thanks @Yozhef for implementing the remaining tests. A couple small adjustments and this should be all set!

2021-03-22 10:45 UTC, jrushlow commented on .github/workflows/ci.yaml
> +name: CI
We should keep the name as is for consistency with other Symfony CI Runs

2021-03-22 10:45 UTC, jrushlow commented on .github/workflows/ci.yaml
> -    composer-validate:
The `composer-validate` job needs to stay and should only be executed with the `--strict` flag. I'm ok with this job living in `static-analysis.yaml`

2021-03-22 10:45 UTC, jrushlow commented on .github/workflows/ci.yaml
> +              run: composer validate --no-check-publish
Does not need to run with the matrix

2021-03-22 10:54 UTC, Yozhef commented
@jrushlow thanks corrected

2021-03-22 10:58 UTC, jrushlow approved these changes

2021-03-22 10:58 UTC, merged

2021-03-22 10:59 UTC, jrushlow commented
Thanks again @Yozhef!